using Alaska.Models;
using AlaskaLib.Models;
using System.Text.Json.Serialization;

namespace Alaska;

[JsonSerializable(typeof(OutletViewModel))]
[JsonSerializable(typeof(Outlet))]
[JsonSerializable(typeof(DropdownOption))]
[JsonSerializable(typeof(Record))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(Product))]
[JsonSerializable(typeof(List<Product>))]
[JsonSerializable(typeof(ProductCategory))]
[JsonSerializable(typeof(List<ProductCategory>))]
[JsonSerializable(typeof(StockInfo))]
[JsonSerializable(typeof(ProductViewModel))]
[JsonSerializable(typeof(Customer))]
[JsonSerializable(typeof(List<CustomerModel>))]
[JsonSerializable(typeof(List<CustomerGroup>))]
[JsonSerializable(typeof(Menu))]
[JsonSerializable(typeof(MenuGroup))]
[JsonSerializable(typeof(List<Menu>))]
[JsonSerializable(typeof(List<MenuGroup>))]
[JsonSerializable(typeof(Bank))]
[JsonSerializable(typeof(Account))]
[JsonSerializable(typeof(List<Bank>))]
[JsonSerializable(typeof(AccountModel))]
[JsonSerializable(typeof(Supplier))]
[JsonSerializable(typeof(SupplierModel))]
[JsonSerializable(typeof(SupplierGroup))]
[JsonSerializable(typeof(List<SupplierGroup>))]
[JsonSerializable(typeof(CommonResult))]
[JsonSerializable(typeof(Department))]
[JsonSerializable(typeof(List<Department>))]
[JsonSerializable(typeof(Role))]
[JsonSerializable(typeof(RoleModel))]
[JsonSerializable(typeof(List<Role>))]
[JsonSerializable(typeof(Employee))]
[JsonSerializable(typeof(List<Employee>))]
[JsonSerializable(typeof(EmployeeModel))]
[JsonSerializable(typeof(Promo))]
[JsonSerializable(typeof(Login))]
[JsonSerializable(typeof(LoginModel))]
[JsonSerializable(typeof(RNEType))]
[JsonSerializable(typeof(Page))]
[JsonSerializable(typeof(Period))]
[JsonSerializable(typeof(ApplicationMenuAccess))]
[JsonSerializable(typeof(ApplicationMenuGroup))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(UserProfileInfo))]
[JsonSerializable(typeof(StoreInfo))]
[JsonSerializable(typeof(Sale))]
[JsonSerializable(typeof(SaleItem))]
[JsonSerializable(typeof(ProductInfo))]
[JsonSerializable(typeof(SaleItemRequest))]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}